### ISSUE TITLE
Incorporate science_week into time.py

### ISSUE THREAD

**Issue by planetarymike** [lasp/maven_iuvs#11]
Hey Kyle,

Seems to me that science_week.py belongs in time.py with the other timekeeping routines. Could you move this if you have no objections?

A related issue is where to keep the tests-- moving these to a subdirectory a la numpy would be my preference. Do we want to implement a way to run these automatically, or just have them hang out in the testing directory in case anyone needs to run them?

**Comment by kconnour** [comment]
I actually found a small mistake in my science week class so I'm going to try to pull that in now. I'll close this request but let's discuss these topics in the pull request thread.

**Comment by kconnour** [comment]
See #12 for continued discussion in the pull request.
