### ISSUE TITLE
add author names to contributed routines

### ISSUE THREAD

**Issue by planetarymike** [lasp/maven_iuvs#14]
In our initial meeting we settled on an "original author decides" approach to how we're planning to merge changes to existing routines. 

To do this we'll need to keep track of the original author of each routine--- how should we do this? 

I suggest we add a field to all docstrings with the author name. 

We should also check that these author fields exist when merging pull requests--- we may need to get a PR checklist going.

**Comment by zachariahmilby** [comment]
I think that's a good idea, similar to the doc string equivalents in IDL routines?

**Comment by planetarymike** [comment]
I'm not sure what's in the IDL routines---- I was thinking we'd add something to the docstring like

>`Author`
>`---------`
>`Mike Chaffin`

According to the [numpy style guide](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard), the author's name doesn't belong in the docstring, so maybe we add it as a comment just after the docstring?

**Comment by zachariahmilby** [comment]
What if it's just the last sentence of the description in the doctoring. So, for `calculate_calibration_curve`, the docstring would  start like:

`"""Generates a spectral calibration curve in DN/kR. The FITS file
    (from which the spectrum comes) provides the necessary calibration
    factors. Note: this requires a level 1B FITS file, it cannot
    produce a "de-calibration" curve from a level 1C file. Written by Zachariah Milby.`

or something like that.

**Comment by planetarymike** [comment]
That's definitely more compact than my proposal. It adds author information to the output of every help call though--- and could lead to emails rather than opening issues on the github page.

Maybe 'author' is the wrong way to think about this? Really we just want to keep track of who's responsible for merging PRs to that routine, which only the maintainers of the repo need to know about. Could this work?

`def routine():`
`"""Comprehensive docstring"""`
`# managed by Mike Chaffin`

**Comment by zachariahmilby** [comment]
That's fine with me

**Comment by planetarymike** [comment]
OK--- sounds like we have a big PR coming to identify the maintainer of every routine in the module.

**Comment by kconnour** [comment]
I have a different proposal.. one that gets more beneficial with time.

When you click on any file through Github [like this one](https://github.com/lasp/maven_iuvs/blob/master/maven_iuvs/time.py), there's "History" info in the top right that shows everyone who's made edits to the file along with what edits they made. I think anyone who's editing a file can/should look at the history to determine how to proceed with their pull request. Benefits:
* Everyone has a unique username. If Mike GenericName joined the team but I knew you (Mike C) wrote a file, I wouldn't necessarily know which Mike is @planetarymike. This tells us exactly who to contact via their unique name. In the same vein, if someone outside the team just saw someone's name, they may not know any way at all to contact the original author about contributing.
* If you look at the history you can see who's been editing which sections so you know who to ask about a pull request. This avoids the issue of having to remember every single time to update the docstring with your name. For example if Bob writes a function and then Alice modifies it, there'd be no ambiguity that Alice should be the one to look at any changes that Charlie makes. If Alice forgot to update the docstring, Bob would get requests about functions he's not necessarily familiar with.
* If Bob is the maintainer of a function but leaves the IUVS team, there's still info on the next best contributor through the history. This is absent from the docstring.
*  It's also a bit more private, though I guess this isn't too much of a concern in the planetary sciences. 

I'll go with the flow but these are just my thoughts. I think @planetarymike deleted the original history when renaming PyUVS to maven_iuvs---which is really easy to do---so for the time being it shows him as the only author for the entire module. But I think moving forward it'll become apparent who's responsible for which parts of which files.

**Comment by planetarymike** [comment]
We could roll back that PR and try to preserve the history in the move?

I like this because it's managed automatically--- I'll propose some changes to the auto PR text to reflect this.

**Comment by planetarymike** [comment]
I think we're good to close this, right?

**Comment by kconnour** [comment]
Since there was a bit of discussion before my suggestion, I'd like to get buy-in from @zachariahmilby before closing so we're all on the same page.

**Comment by zachariahmilby** [comment]
Sure this is all fine to me, go ahead and close.

On Dec 22, 2020, at 3:41 PM, kconnour <notifications@github.com<mailto:notifications@github.com>> wrote:



Since there was a bit of discussion before my suggestion, I'd like to get buy-in from @zachariahmilby<https://github.com/zachariahmilby> before closing so we're all on the same page.
