### ISSUE TITLE
fix first run of sync_data

### ISSUE THREAD

**Issue by planetarymike** [lasp/maven_iuvs#43]
Eryn ran into an issue where the IUVS VM wasn't on the list of known hosts, so the package call appeared to hang in the browser

**Comment by emcangi** [comment]
A fix is included in PR https://github.com/lasp/maven_iuvs/pull/54

**Comment by emcangi** [comment]
Fix included in PR https://github.com/lasp/maven_iuvs/pull/54, commit https://github.com/lasp/maven_iuvs/pull/54/commits/8acb2ecfa8243ad311f039e3f788dddbf2d7b90f

**Comment by planetarymike** [comment]
Fixed by #57
