### ISSUE TITLE
Organization of routines in data.py , variables.py

### ISSUE THREAD

**Issue by planetarymike** [lasp/maven_iuvs#7]
I'm wondering if some rearrangement of the routines is appropriate... the get_calibration_curve routine in data.py and many of the variables in variables.py refer to IUVS instrument specific quantities or procedures. Should we move these into a more descriptive submodule, like instrument.py ?

**Comment by planetarymike** [comment]
Similarly, mirror_dn_to_deg in miscellaneous.py

**Comment by kconnour** [comment]
I tend to think this is a good idea, although I'm little confused about your claim of IUVS specificness---it looks to me that every single function in data.py is somehow specific to IUVS. I haven't found the time to work more on my ballyhooed files classes, which may be beneficial for this sort of thing. Regardless of whether or not you like my idea, I think the more organization the better. 

I think it would be a good idea to put these functions in files that describe on what data they can act. Some functions in data.py are only valid on l1b files, whereas some seem like they can work on data from any level.

**Comment by planetarymike** [comment]
I was thinking about functions specific to the instrument hardware. You're right that the whole package is specific to IUVS :)

There are definitely some other organization issues we should deal with. I was thinking about this specific issue that could result in a PR later on, so if there are others, let's open some other issues!

**Comment by planetarymike** [comment]
This is closed with the incorporation of PR #10
