### ISSUE TITLE
place instructions for installation in Readme

### ISSUE THREAD

**Issue by planetarymike** [lasp/maven_iuvs#8]
Kyle or Zac, can you put some recommended instructions for installation in the README, so they appear on the main page? This might also include some info on setting up an appropriate virtual environment.

**Comment by kconnour** [comment]
I can add some instructions in the README sometime soon. I'm also happy to add instructions on how to use a venv but I think this should be a separate document at the project level since it's more about showing people how to use tools available to them instead of this specific tool.

**Comment by planetarymike** [comment]
Sounds good. It might be as simple as 

> If you want to contribute code later on, follow the instructions [here](https://numpy.org/doc/stable/dev/) to fork the repo to your github page and clone from there. If you're sure you won't contribute code, you can clone this repo directly.
>
> Once the repo is cloned, you may want to create a virtual environment in the maven_iuvs folder:
> `python3 -m venv env`
>
> After that, you can install the package with 
> `pip install .`
> to make it available anywhere on your system.

**Comment by planetarymike** [comment]
Closed through #12
