### ISSUE TITLE
naming conventions, move data

### ISSUE THREAD

**Issue by kconnour** [lasp/maven_iuvs#9]
Short description: I believe we ought to either rename the repo or rename the module. I think we also ought to move the data to the project level. 

Long description: In my experience a repo is often thought of as a "project" and the useful code is kept within the project as a "module". Also in my experience, it's much easier to understand how code works if the project and module have the same name. 

It might be best to explain via examples. Check out numpy: https://github.com/numpy/numpy. Within the project, they have the numpy folder (the module), which is the bit of code copied to your computer every time you pip install numpy. They also have files related to the module (like README.md) but aren't part of module, as well as a documentation folder that's clearly part of the project but not the module. I find this fairly clean and it's easy for me to tell how the project is organized. For a slightly messier example, check out matplotlib: https://github.com/matplotlib/matplotlib. Every time you pip install matplotlib you actually install 2 modules within the lib folder, but even in this case one of them is named matplotlib; that is, they have a matplotlib module within the matplotlib project. 

So to my proposal. I think that like these libraries, we ought to have the project and module have the same names. To someone familiar with this project/module structure I think it'll be less confusing than having to remember that maven_iuvs is the project and PyUVS is the module. It's also easier to find---anyone wanting to pip install PyUVS before it's available on PyPI (if ever...) would have to know/remember the PyUVS code is on the maven_iuvs project page. 

I also propose that we move the ancillary folder out of the module and into the project level, although I feel less strongly about this proposal since other major projects don't do this (namely, sklearn). To me it makes the most sense to not make the module bloated with all sorts of files that users may or may not want, but if the users want the ancillary files they can get them from the project's repository. However the counterargument is that if we force users to download ancillary files, we are closer to ensuring that they always use the "correct" files. 

I'm open to discussions about these topics and just wanted to throw project structure ideas out there.

**Comment by planetarymike** [comment]
Agreed on the name of the repo, this should be relatively easy to change. As much as I like PyUVS, switching to maven_iuvs would make things slightly more transparent to the end user and avoid having to use the shift key twice to type the name.

On ancillary files, I think these belong in the repo, since there are functions in the repo that break without them--- I'm planning to introduce some more of these that relate to instrument LSF, FUV flatfield, etc. Without those files the repo is broken, so I think we have no choice but to keep them--- though we should audit contributions to make sure the file sizes and need for the file is reasonable.

**Comment by planetarymike** [comment]
Thoughts on changing the base module name, @zachariahmilby ? maven_iuvs would be my preference for the reasons Kyle listed above.

**Comment by zachariahmilby** [comment]
Sure, you guys definitely know a lot more about all this than I do.
